<?= $this->headTitle('Books'); ?>

<h4>Books</h4>
<br />

<div class="d-flex justify-content-end">
    <a href="<?= $this->url('post', ['action' => 'add']) ?>"
        class="btn btn-primary">Add</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Author</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($bookList as $key => $book): ?>
                <tr>
                    <td><?= ++$key; ?>
                    </td>
                    <td><?= $this->escapeHtml($book->getTitle()) ?>
                    </td>
                    <td><?= $this->escapeHtml($book->getDescription()) ?>
                    </td>
                    <td><?= $this->escapeHtml($book->getAuthor()->getName()) ?>
                    </td>
                    <td>
                        <a href="<?= $this->url('post', ['action' => 'edit', 'id' => $book->getId()]) ?>"
                            class="btn btn-primary">Edit</a>
                        <a href="<?= $this->url('post', ['action' => 'delete', 'id' => $book->getId()]) ?>"
                            class="btn btn-secondary">Delete</a>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>