<h3>Books</h3>
<br />

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Title</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($bookList as $book): ?>
                <tr>
                    <td>1</td>
                    <td><?= $this->escapeHtml($book->getTitle()) ?>
                    </td>
                    <td><?= $this->escapeHtml($book->getDescription()) ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>