<?= $this->headTitle('Add book'); ?>

<label class="page-header">Add Book</label>

<?= $this->form()->openTag($form) ?>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <?= $this->formLabel($form->get('title'), 'Title'); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description'), 'Description'); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <?= $this->formElement($form->get('submit')) ?>
        <a href="<?= $this->url('book', ['action' => 'index']) ?>"
            class="btn btn-secondary">Back</a>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            <?= $this->formLabel($form->get('author_id'), 'Author'); ?>
            <?= $this->formElement($form->get('author_id')); ?>
            <?= $this->formElementErrors($form->get('author_id')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('category_ids'), 'Categories') ?>
            <?= $this->formElement($form->get('category_ids')) ?>
            <?= $this->formElementErrors($form->get('category_ids')) ?>
        </div>
    </div>
</div>
<?= $this->form()->closeTag();
