<?= $this->headTitle('Add book'); ?>

<h4>Add Book</h4>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title'), 'Title'); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description'), 'Description'); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <?= $this->formElement($form->get('submit')) ?>
        <a href="<?= $this->url('book', ['action' => 'index']) ?>"
            class="btn btn-secondary">Back</a>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>