<?php
$form = $this->form;
$form->get('title')->setAttributes([
    'class'=>'form-control',
    ]);
$form->get('description')->setAttributes([
    'class'=>'form-control',
    'rows'=> 6
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-primary'
]);
$form->prepare();

?>

<h4>Add Book</h4>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title'), 'Title') ?>
            <?= $this->formElement($form->get('title')) ?>
            <?= $this->formElementErrors($form->get('title')) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description'), 'Description') ?>
            <?= $this->formElement($form->get('description')) ?>
            <?= $this->formElementErrors($form->get('description')) ?>
        </div>

        <?= $this->formElement($form->get('submit')) ?>
        <a href="<?= $this->url('book', ['action' => 'index']) ?>"
            class="btn btn-secondary">Back</a>

        <?= $this->form()->closeTag(); ?>

    </div>

</div>